- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World again !"
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']